name: ' Test Next Major'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  workflowDepth: 1
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ vars.ALPACA_BACKEND_URL }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ ubuntu-latest ]
    outputs:
      projects: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
      projectDependenciesJson: ${{ steps.determineProjectsToBuild.outputs.ProjectDependenciesJson }}
      buildOrderJson: ${{ steps.determineProjectsToBuild.outputs.BuildOrderJson }}
      workflowDepth: ${{ steps.DetermineWorkflowDepth.outputs.WorkflowDepth }}
      artifactsRetentionDays: ${{ steps.DetermineWorkflowDepth.outputs.ArtifactsRetentionDays }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@customize
        with:
          shell: pwsh

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@customize
        with:
          shell: pwsh

      - name: Read settings
        id: ReadSettings
        uses: freddydk/AL-Go/Actions/ReadSettings@customize
        with:
          shell: pwsh
          get: useGitSubmodules,shortLivedArtifactsRetentionDays

      - name: Read submodules token
        id: ReadSubmodulesToken
        if: env.useGitSubmodules != 'false' && env.useGitSubmodules != ''
        uses: freddydk/AL-Go/Actions/ReadSecrets@customize
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: '-gitSubmodulesToken'

      - name: Checkout Submodules
        if: env.useGitSubmodules != 'false' && env.useGitSubmodules != ''
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          submodules: ${{ env.useGitSubmodules }}
          token: '${{ fromJson(steps.ReadSubmodulesToken.outputs.Secrets).gitSubmodulesToken }}'

      - name: Determine Workflow Depth
        id: DetermineWorkflowDepth
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "WorkflowDepth=$($env:workflowDepth)"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ArtifactsRetentionDays=$($env:shortLivedArtifactsRetentionDays)"

      - name: Determine Projects To Build
        id: determineProjectsToBuild
        uses: freddydk/AL-Go/Actions/DetermineProjectsToBuild@customize
        with:
          shell: pwsh
          maxBuildDepth: ${{ env.workflowDepth }}

  Build:
    needs: [ Initialization, CustomJob-CreateAlpaca-Container ]
    if: (!failure()) && (!cancelled()) && fromJson(needs.Initialization.outputs.buildOrderJson)[0].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[0].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ matrix.githubRunnerShell }}
      runsOn: ${{ matrix.githubRunner }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      secrets: 'licenseFileUrl,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'
      artifactsRetentionDays: ${{ fromJson(needs.Initialization.outputs.artifactsRetentionDays) }}
      artifactsNameSuffix: 'NextMajor'
      needsContext:  ${{ toJson(needs) }}

  PostProcess:
    needs: [ Initialization, Build, CustomJob-RemoveAlpaca-Container ]
    if: always()
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@customize
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}

  CustomJob-CreateAlpaca-Container:
    if: ${{ always() }}
    runs-on: [ ubuntu-latest ]
    permissions: read-all
    outputs:
      containerID: ${{ steps.CreateContainer.outputs.containerID }}
      containerUser: ${{ steps.CreateContainer.outputs.containerUser }}
      containerPassword: ${{ steps.CreateContainer.outputs.containerPassword }}
      containerURL: ${{ steps.CreateContainer.outputs.containerURL }}
    steps:
      - uses: actions/checkout@v4
      - id: CreateContainer
        name: Create COSMO Alpaca Container
        shell: pwsh
        run: |
          ./.alpaca/PowerShell/Create-AlpacaContainer.ps1 -token "${{ secrets.GITHUB_TOKEN }}"

  CustomJob-RemoveAlpaca-Container:
    needs: [ CustomJob-CreateAlpaca-Container, Build ]
    if: ${{ always() }}
    runs-on: [ ubuntu-latest ]
    env:
      needsContext:  ${{ toJson(needs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Remove COSMO Alpaca Container
        shell: pwsh
        run: |
          ./.alpaca/PowerShell/Remove-AlpacaContainer.ps1 -token "${{ secrets.GITHUB_TOKEN }}"
