name: 'Pull Request Build'

on:
  pull_request_target:
    branches: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

permissions:
  actions: read
  contents: read
  id-token: write
  pull-requests: read

env:
  workflowDepth: 1
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ vars.ALPACA_BACKEND_URL }}

jobs:
  PregateCheck:
    if: (github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name) && (github.event_name != 'pull_request')
    runs-on: windows-latest
    steps:
      - uses: freddydk/AL-Go/Actions/VerifyPRChanges@customize

  Initialization:
    needs: [ PregateCheck ]
    if: (!failure() && !cancelled())
    runs-on: [ ubuntu-latest ]
    outputs:
      projects: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
      projectDependenciesJson: ${{ steps.determineProjectsToBuild.outputs.ProjectDependenciesJson }}
      buildOrderJson: ${{ steps.determineProjectsToBuild.outputs.BuildOrderJson }}
      baselineWorkflowRunId: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowRunId }}
      baselineWorkflowSHA: ${{ steps.determineProjectsToBuild.outputs.BaselineWorkflowSHA }}
      workflowDepth: ${{ steps.DetermineWorkflowDepth.outputs.WorkflowDepth }}
      artifactsRetentionDays: ${{ steps.DetermineWorkflowDepth.outputs.ArtifactsRetentionDays }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Dump Workflow Information
        uses: freddydk/AL-Go/Actions/DumpWorkflowInfo@customize
        with:
          shell: pwsh

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true
          ref: ${{ github.event_name == 'pull_request' && github.sha || format('refs/pull/{0}/merge', github.event.pull_request.number) }}

      - name: Initialize the workflow
        id: init
        uses: freddydk/AL-Go/Actions/WorkflowInitialize@customize
        with:
          shell: pwsh

      - name: Read settings
        id: ReadSettings
        uses: freddydk/AL-Go/Actions/ReadSettings@customize
        with:
          shell: pwsh
          get: shortLivedArtifactsRetentionDays

      - name: Determine Workflow Depth
        id: DetermineWorkflowDepth
        run: |
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "WorkflowDepth=$($env:workflowDepth)"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ArtifactsRetentionDays=$($env:shortLivedArtifactsRetentionDays)"

      - name: Determine Projects To Build
        id: determineProjectsToBuild
        uses: freddydk/AL-Go/Actions/DetermineProjectsToBuild@customize
        with:
          shell: pwsh
          maxBuildDepth: ${{ env.workflowDepth }}

  Build:
    needs: [ Initialization, CustomJob-CreateAlpaca-Container ]
    if: (!failure()) && (!cancelled()) && fromJson(needs.Initialization.outputs.buildOrderJson)[0].projectsCount > 0
    strategy:
      matrix:
        include: ${{ fromJson(needs.Initialization.outputs.buildOrderJson)[0].buildDimensions }}
      fail-fast: false
    name: Build ${{ matrix.projectName }} (${{ matrix.buildMode }})
    uses: ./.github/workflows/_BuildALGoProject.yaml
    secrets: inherit
    with:
      shell: ${{ matrix.githubRunnerShell }}
      runsOn: ${{ matrix.githubRunner }}
      checkoutRef: ${{ github.event_name == 'pull_request' && github.sha || format('refs/pull/{0}/merge', github.event.pull_request.number) }}
      project: ${{ matrix.project }}
      projectName: ${{ matrix.projectName }}
      buildMode: ${{ matrix.buildMode }}
      projectDependenciesJson: ${{ needs.Initialization.outputs.projectDependenciesJson }}
      baselineWorkflowRunId: ${{ needs.Initialization.outputs.baselineWorkflowRunId }}
      baselineWorkflowSHA: ${{ needs.Initialization.outputs.baselineWorkflowSHA }}
      secrets: 'licenseFileUrl,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString'
      artifactsRetentionDays: ${{ fromJson(needs.Initialization.outputs.artifactsRetentionDays) }}
      artifactsNameSuffix: 'PR${{ github.event.number }}'
      needsContext:  ${{ toJson(needs) }}
      useArtifactCache: true

  StatusCheck:
    needs: [ Initialization, Build, CustomJob-RemoveAlpaca-Container ]
    if: (!cancelled())
    runs-on: [ ubuntu-latest ]
    name: Pull Request Status Check
    steps:
      - name: Pull Request Status Check
        id: PullRequestStatusCheck
        uses: freddydk/AL-Go/Actions/PullRequestStatusCheck@customize
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh

      - name: Finalize the workflow
        id: PostProcess
        uses: freddydk/AL-Go/Actions/WorkflowPostProcess@customize
        if: success() || failure()
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}

  CustomJob-CreateAlpaca-Container:
    if: ${{ always() }}
    runs-on: [ ubuntu-latest ]
    permissions: read-all
    outputs:
      containerID: ${{ steps.CreateContainer.outputs.containerID }}
      containerUser: ${{ steps.CreateContainer.outputs.containerUser }}
      containerPassword: ${{ steps.CreateContainer.outputs.containerPassword }}
      containerURL: ${{ steps.CreateContainer.outputs.containerURL }}
    steps:
      - uses: actions/checkout@v4
      - id: CreateContainer
        name: Create COSMO Alpaca Container
        shell: pwsh
        run: |
          ./.alpaca/PowerShell/Create-AlpacaContainer.ps1 -token "${{ secrets.GITHUB_TOKEN }}"

  CustomJob-RemoveAlpaca-Container:
    needs: [ CustomJob-CreateAlpaca-Container, Build ]
    if: ${{ always() }}
    runs-on: [ ubuntu-latest ]
    env:
      needsContext:  ${{ toJson(needs) }}
    steps:
      - uses: actions/checkout@v4
      - name: Remove COSMO Alpaca Container
        shell: pwsh
        run: |
          ./.alpaca/PowerShell/Remove-AlpacaContainer.ps1 -token "${{ secrets.GITHUB_TOKEN }}"
